const productsJson = [
  {
    "iD": 449,
    "ParentID": null,
    "ProductTypeID": 1,
    "CustomsDeclarationID": null,
    "Country_Manufacture_CompanyID": null,
    "SizeID": 257,
    "GSMID": 9,
    "GradeID": 7,
    "QualityID": 20,
    "ProductColorID": 1,
    "date": "2020-01-21 12:56:47",
    "sheets": null,
    "barcode": "2822426428001",
    "fiberLines": "Width",
    "comments": null,
    "status": "NONE",
    "parents": [],
    "sizes": {"iD": 257, "width": 540, "length": 0},
    "gsms": {"iD": 9, "gsm": 320},
    "countries_manufactures": null,
    "qualities": {"iD": 20, "name": "gestr. Duplex Karton graue RS"},
    "grades": {"iD": 7, "name": "GD: A"},
    "customs_declarations": null,
    "products_types": {
      "iD": 1,
      "GradeID": 1,
      "name": "MM",
      "unit": "KG",
      "sellPrice": 0.77500000000000002220446049250313080847263336181640625,
      "purchasePrice": 0.58999999999999996891375531049561686813831329345703125,
      "image": "saffoury.com/SaffouryPaper2/Images/mmLogo.png",
      "comments": null,
      "availability": 0,
      "grades": {"iD": 1, "name": "GT A"}
    },
    "products_colors": {
      "iD": 1,
      "top": "ffffff",
      "middle": "dbd8e0",
      "back": "ab8153"
    },
    "cut_requests": [],
    "cut_requests_count": 0,
    "order_refunds_order_details": [],
    "order_refunds_order_details_count": 0,
    "orders_details": [],
    "orders_details_count": 0,
    "childs": [],
    "childs_count": 0,
    "products_inputs_details": [],
    "products_inputs_details_count": 0,
    "products_outputs_details": [],
    "products_outputs_details_count": 0,
    "purchases_details": [],
    "purchases_details_count": 0,
    "purchases_refunds_purchases_details": [],
    "purchases_refunds_purchases_details_count": 0,
    "reservation_invoice_details": [],
    "reservation_invoice_details_count": 0,
    "transfers_details": [],
    "transfers_details_count": 0,
    "inStock": null,
    "pending_reservation_invoice": null
  },
  {
    "iD": 450,
    "ParentID": null,
    "ProductTypeID": 1,
    "CustomsDeclarationID": null,
    "Country_Manufacture_CompanyID": null,
    "SizeID": 257,
    "GSMID": 9,
    "GradeID": 7,
    "QualityID": 20,
    "ProductColorID": 1,
    "date": "2020-01-21 12:56:47",
    "sheets": null,
    "barcode": "2822426428002",
    "fiberLines": "Width",
    "comments": null,
    "status": "NONE",
    "parents": [],
    "sizes": {"iD": 257, "width": 540, "length": 0},
    "gsms": {"iD": 9, "gsm": 320},
    "countries_manufactures": null,
    "qualities": {"iD": 20, "name": "gestr. Duplex Karton graue RS"},
    "grades": {"iD": 7, "name": "GD: A"},
    "customs_declarations": null,
    "products_types": {
      "iD": 1,
      "GradeID": 1,
      "name": "MM",
      "unit": "KG",
      "sellPrice": 0.77500000000000002220446049250313080847263336181640625,
      "purchasePrice": 0.58999999999999996891375531049561686813831329345703125,
      "image": "saffoury.com/SaffouryPaper2/Images/mmLogo.png",
      "comments": null,
      "availability": 0,
      "grades": {"iD": 1, "name": "GT A"}
    },
    "products_colors": {
      "iD": 1,
      "top": "ffffff",
      "middle": "dbd8e0",
      "back": "ab8153"
    },
    "cut_requests": [],
    "cut_requests_count": 0,
    "order_refunds_order_details": [],
    "order_refunds_order_details_count": 0,
    "orders_details": [],
    "orders_details_count": 0,
    "childs": [],
    "childs_count": 0,
    "products_inputs_details": [],
    "products_inputs_details_count": 0,
    "products_outputs_details": [],
    "products_outputs_details_count": 0,
    "purchases_details": [],
    "purchases_details_count": 0,
    "purchases_refunds_purchases_details": [],
    "purchases_refunds_purchases_details_count": 0,
    "reservation_invoice_details": [],
    "reservation_invoice_details_count": 0,
    "transfers_details": [],
    "transfers_details_count": 0,
    "inStock": null,
    "pending_reservation_invoice": null
  },
  {
    "iD": 451,
    "ParentID": null,
    "ProductTypeID": 1,
    "CustomsDeclarationID": null,
    "Country_Manufacture_CompanyID": null,
    "SizeID": 348,
    "GSMID": 3,
    "GradeID": 7,
    "QualityID": 18,
    "ProductColorID": 1,
    "date": "2020-01-21 12:56:47",
    "sheets": null,
    "barcode": "2765243718001",
    "fiberLines": "Length",
    "comments": null,
    "status": "NONE",
    "parents": [],
    "sizes": {"iD": 348, "width": 520, "length": 600},
    "gsms": {"iD": 3, "gsm": 450},
    "countries_manufactures": null,
    "qualities": {"iD": 18, "name": "Multicolor Mirabell"},
    "grades": {"iD": 7, "name": "GD: A"},
    "customs_declarations": null,
    "products_types": {
      "iD": 1,
      "GradeID": 1,
      "name": "MM",
      "unit": "KG",
      "sellPrice": 0.77500000000000002220446049250313080847263336181640625,
      "purchasePrice": 0.58999999999999996891375531049561686813831329345703125,
      "image": "saffoury.com/SaffouryPaper2/Images/mmLogo.png",
      "comments": null,
      "availability": 0,
      "grades": {"iD": 1, "name": "GT A"}
    },
    "products_colors": {
      "iD": 1,
      "top": "ffffff",
      "middle": "dbd8e0",
      "back": "ab8153"
    },
    "cut_requests": [],
    "cut_requests_count": 0,
    "order_refunds_order_details": [],
    "order_refunds_order_details_count": 0,
    "orders_details": [],
    "orders_details_count": 0,
    "childs": [],
    "childs_count": 0,
    "products_inputs_details": [],
    "products_inputs_details_count": 0,
    "products_outputs_details": [],
    "products_outputs_details_count": 0,
    "purchases_details": [],
    "purchases_details_count": 0,
    "purchases_refunds_purchases_details": [],
    "purchases_refunds_purchases_details_count": 0,
    "reservation_invoice_details": [],
    "reservation_invoice_details_count": 0,
    "transfers_details": [],
    "transfers_details_count": 0,
    "inStock": null,
    "pending_reservation_invoice": null
  },
  {
    "iD": 452,
    "ParentID": null,
    "ProductTypeID": 1,
    "CustomsDeclarationID": null,
    "Country_Manufacture_CompanyID": null,
    "SizeID": 348,
    "GSMID": 3,
    "GradeID": 7,
    "QualityID": 18,
    "ProductColorID": 1,
    "date": "2020-01-21 12:56:47",
    "sheets": null,
    "barcode": "2765243718002",
    "fiberLines": "Length",
    "comments": null,
    "status": "NONE",
    "parents": [],
    "sizes": {"iD": 348, "width": 520, "length": 600},
    "gsms": {"iD": 3, "gsm": 450},
    "countries_manufactures": null,
    "qualities": {"iD": 18, "name": "Multicolor Mirabell"},
    "grades": {"iD": 7, "name": "GD: A"},
    "customs_declarations": null,
    "products_types": {
      "iD": 1,
      "GradeID": 1,
      "name": "MM",
      "unit": "KG",
      "sellPrice": 0.77500000000000002220446049250313080847263336181640625,
      "purchasePrice": 0.58999999999999996891375531049561686813831329345703125,
      "image": "saffoury.com/SaffouryPaper2/Images/mmLogo.png",
      "comments": null,
      "availability": 0,
      "grades": {"iD": 1, "name": "GT A"}
    },
    "products_colors": {
      "iD": 1,
      "top": "ffffff",
      "middle": "dbd8e0",
      "back": "ab8153"
    },
    "cut_requests": [],
    "cut_requests_count": 0,
    "order_refunds_order_details": [],
    "order_refunds_order_details_count": 0,
    "orders_details": [],
    "orders_details_count": 0,
    "childs": [],
    "childs_count": 0,
    "products_inputs_details": [],
    "products_inputs_details_count": 0,
    "products_outputs_details": [],
    "products_outputs_details_count": 0,
    "purchases_details": [],
    "purchases_details_count": 0,
    "purchases_refunds_purchases_details": [],
    "purchases_refunds_purchases_details_count": 0,
    "reservation_invoice_details": [],
    "reservation_invoice_details_count": 0,
    "transfers_details": [],
    "transfers_details_count": 0,
    "inStock": null,
    "pending_reservation_invoice": null
  },
  {
    "iD": 453,
    "ParentID": null,
    "ProductTypeID": 1,
    "CustomsDeclarationID": null,
    "Country_Manufacture_CompanyID": null,
    "SizeID": 348,
    "GSMID": 3,
    "GradeID": 7,
    "QualityID": 18,
    "ProductColorID": 1,
    "date": "2020-01-21 12:56:47",
    "sheets": null,
    "barcode": "2765243718003",
    "fiberLines": "Length",
    "comments": null,
    "status": "NONE",
    "parents": [],
    "sizes": {"iD": 348, "width": 520, "length": 600},
    "gsms": {"iD": 3, "gsm": 450},
    "countries_manufactures": null,
    "qualities": {"iD": 18, "name": "Multicolor Mirabell"},
    "grades": {"iD": 7, "name": "GD: A"},
    "customs_declarations": null,
    "products_types": {
      "iD": 1,
      "GradeID": 1,
      "name": "MM",
      "unit": "KG",
      "sellPrice": 0.77500000000000002220446049250313080847263336181640625,
      "purchasePrice": 0.58999999999999996891375531049561686813831329345703125,
      "image": "saffoury.com/SaffouryPaper2/Images/mmLogo.png",
      "comments": null,
      "availability": 0,
      "grades": {"iD": 1, "name": "GT A"}
    },
    "products_colors": {
      "iD": 1,
      "top": "ffffff",
      "middle": "dbd8e0",
      "back": "ab8153"
    },
    "cut_requests": [],
    "cut_requests_count": 0,
    "order_refunds_order_details": [],
    "order_refunds_order_details_count": 0,
    "orders_details": [],
    "orders_details_count": 0,
    "childs": [],
    "childs_count": 0,
    "products_inputs_details": [],
    "products_inputs_details_count": 0,
    "products_outputs_details": [],
    "products_outputs_details_count": 0,
    "purchases_details": [],
    "purchases_details_count": 0,
    "purchases_refunds_purchases_details": [],
    "purchases_refunds_purchases_details_count": 0,
    "reservation_invoice_details": [],
    "reservation_invoice_details_count": 0,
    "transfers_details": [],
    "transfers_details_count": 0,
    "inStock": null,
    "pending_reservation_invoice": null
  }
];
final loginJson = {
  "iD": 1,
  "ParentID": null,
  "userlevelid": -2,
  "name": "Qussai Al-Saffoury",
  "phone": "0933326882",
  "password": "933326880",
  "email": "geaquzzil@gmail.com",
  "token":
      "cN3h1E8CQ2maw4N_s-JveB:APA91bG3D_y83_l3VbYlyARs81FtLg9SbFpMHh9aFx1gLtrGR-u45cRIBP22QKLFPsW3s_cJwhRpXxV29rja8dw_-VgmI9DsFMrXmHnwPJqXZM8YiSQ1ywhYC81Y4B3X6-Vs0umCyCU2",
  "activated": 1,
  "date": "2019-10-06 00:00:00",
  "city": null,
  "address": null,
  "profile":
      "a:2:{s:15:\"LoginRetryCount\";i:1;s:20:\"LastBadLoginDateTime\";s:19:\"2019/10/21 19:56:51\";}",
  "publish": 1,
  "comments": null,
  "userlevels": {
    "iD": -2,
    "userlevelname": "Administrator",
    "customers": [],
    "customers_count": 0,
    "employees": [],
    "employees_count": 4,
    "permissions_levels": [
      {
        "iD": 101,
        "userlevelid": -2,
        "table_name": "action_exchange_rate",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 102,
        "userlevelid": -2,
        "table_name": "action_block",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 103,
        "userlevelid": -2,
        "table_name": "action_transfer_account",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 104,
        "userlevelid": -2,
        "table_name": "action_notification",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 105,
        "userlevelid": -2,
        "table_name": "action_change_customers_password",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 106,
        "userlevelid": -2,
        "table_name": "text_customers_password",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 107,
        "userlevelid": -2,
        "table_name": "text_transaction_added_by",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 108,
        "userlevelid": -2,
        "table_name": "text_prices_for_customer",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 109,
        "userlevelid": -2,
        "table_name": "text_products_notes",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 110,
        "userlevelid": -2,
        "table_name": "text_purchase_price",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 111,
        "userlevelid": -2,
        "table_name": "text_balance_due",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 112,
        "userlevelid": -2,
        "table_name": "text_balance_due_today",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 113,
        "userlevelid": -2,
        "table_name": "list_product_movement",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 114,
        "userlevelid": -2,
        "table_name": "list_customers_balances",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 115,
        "userlevelid": -2,
        "table_name": "list_block",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 116,
        "userlevelid": -2,
        "table_name": "list_fund",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 117,
        "userlevelid": -2,
        "table_name": "list_dashboard",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 118,
        "userlevelid": -2,
        "table_name": "list_sales",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 119,
        "userlevelid": -2,
        "table_name": "list_profit_loses",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 120,
        "userlevelid": -2,
        "table_name": "account_names",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 121,
        "userlevelid": -2,
        "table_name": "account_names_types",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 122,
        "userlevelid": -2,
        "table_name": "audittrail",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 123,
        "userlevelid": -2,
        "table_name": "countries",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 124,
        "userlevelid": -2,
        "table_name": "countries_manufactures",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 125,
        "userlevelid": -2,
        "table_name": "credits",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 126,
        "userlevelid": -2,
        "table_name": "currency",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 127,
        "userlevelid": -2,
        "table_name": "customers",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 128,
        "userlevelid": -2,
        "table_name": "customers_balances",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 129,
        "userlevelid": -2,
        "table_name": "customs_declarations",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 130,
        "userlevelid": -2,
        "table_name": "customs_declarations_images",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 131,
        "userlevelid": -2,
        "table_name": "cut_request_results",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 132,
        "userlevelid": -2,
        "table_name": "cut_requests",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 133,
        "userlevelid": -2,
        "table_name": "dealers",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 134,
        "userlevelid": -2,
        "table_name": "debits",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 135,
        "userlevelid": -2,
        "table_name": "employees",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 136,
        "userlevelid": -2,
        "table_name": "equalities",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 137,
        "userlevelid": -2,
        "table_name": "equality_credits",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 138,
        "userlevelid": -2,
        "table_name": "equality_debits",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 139,
        "userlevelid": -2,
        "table_name": "extended_order_refund",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 140,
        "userlevelid": -2,
        "table_name": "extended_orders",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 141,
        "userlevelid": -2,
        "table_name": "extended_products_inputs",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 142,
        "userlevelid": -2,
        "table_name": "extended_products_outputs",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 143,
        "userlevelid": -2,
        "table_name": "extended_purchases",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 144,
        "userlevelid": -2,
        "table_name": "extended_purchases_refund",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 145,
        "userlevelid": -2,
        "table_name": "extended_transfers",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 146,
        "userlevelid": -2,
        "table_name": "fund_balance",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 147,
        "userlevelid": -2,
        "table_name": "grades",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 148,
        "userlevelid": -2,
        "table_name": "gsms",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 149,
        "userlevelid": -2,
        "table_name": "incomes",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 150,
        "userlevelid": -2,
        "table_name": "inventory_input",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 151,
        "userlevelid": -2,
        "table_name": "inventory_orders",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 152,
        "userlevelid": -2,
        "table_name": "inventory_orders_refund",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 153,
        "userlevelid": -2,
        "table_name": "inventory_output",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 154,
        "userlevelid": -2,
        "table_name": "inventory_products",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 155,
        "userlevelid": -2,
        "table_name": "inventory_purchases",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 156,
        "userlevelid": -2,
        "table_name": "inventory_purchases_refund",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 157,
        "userlevelid": -2,
        "table_name": "inventory_total_input",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 158,
        "userlevelid": -2,
        "table_name": "inventory_total_output",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 159,
        "userlevelid": -2,
        "table_name": "inventory_transfer_from",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 160,
        "userlevelid": -2,
        "table_name": "inventory_transfer_to",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 161,
        "userlevelid": -2,
        "table_name": "journal_voucher",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 162,
        "userlevelid": -2,
        "table_name": "manufactures",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 163,
        "userlevelid": -2,
        "table_name": "order_refunds_order_details",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 164,
        "userlevelid": -2,
        "table_name": "orders",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 165,
        "userlevelid": -2,
        "table_name": "orders_details",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 166,
        "userlevelid": -2,
        "table_name": "orders_refunds",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 167,
        "userlevelid": -2,
        "table_name": "permissions_levels",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 168,
        "userlevelid": -2,
        "table_name": "phones",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 169,
        "userlevelid": -2,
        "table_name": "phpgen_user_perms",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 170,
        "userlevelid": -2,
        "table_name": "products",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 171,
        "userlevelid": -2,
        "table_name": "products_all_view",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 172,
        "userlevelid": -2,
        "table_name": "products_inputs",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 173,
        "userlevelid": -2,
        "table_name": "products_inputs_details",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 174,
        "userlevelid": -2,
        "table_name": "products_outputs",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 175,
        "userlevelid": -2,
        "table_name": "products_outputs_details",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 176,
        "userlevelid": -2,
        "table_name": "products_prices",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 177,
        "userlevelid": -2,
        "table_name": "products_search_view",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 178,
        "userlevelid": -2,
        "table_name": "products_types",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 179,
        "userlevelid": -2,
        "table_name": "products_web_view",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 180,
        "userlevelid": -2,
        "table_name": "products_web_view_reels",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 181,
        "userlevelid": -2,
        "table_name": "purchases",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 182,
        "userlevelid": -2,
        "table_name": "purchases_details",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 183,
        "userlevelid": -2,
        "table_name": "purchases_refunds",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 184,
        "userlevelid": -2,
        "table_name": "purchases_refunds_purchases_details",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 185,
        "userlevelid": -2,
        "table_name": "qualities",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 186,
        "userlevelid": -2,
        "table_name": "sales",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 187,
        "userlevelid": -2,
        "table_name": "setting",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 188,
        "userlevelid": -2,
        "table_name": "sizes",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 189,
        "userlevelid": -2,
        "table_name": "sizes_cut_requests",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 190,
        "userlevelid": -2,
        "table_name": "spendings",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 191,
        "userlevelid": -2,
        "table_name": "spendings_orders",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 192,
        "userlevelid": -2,
        "table_name": "spendings_transfers",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 193,
        "userlevelid": -2,
        "table_name": "syp_exchange_rate",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 194,
        "userlevelid": -2,
        "table_name": "transfers",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 195,
        "userlevelid": -2,
        "table_name": "transfers_details",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 196,
        "userlevelid": -2,
        "table_name": "userlevels",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 197,
        "userlevelid": -2,
        "table_name": "warehouse",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 198,
        "userlevelid": -2,
        "table_name": "warehouse_employees",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 199,
        "userlevelid": -2,
        "table_name": "wasted_products",
        "print": 1,
        "notification": 1,
        "list": 1,
        "view": 1,
        "add": 1,
        "edit": 1,
        "delete_action": 1
      },
      {
        "iD": 857,
        "userlevelid": -2,
        "table_name": "text_products_quantity",
        "print": 0,
        "notification": 0,
        "list": 1,
        "view": 1,
        "add": 0,
        "edit": 0,
        "delete_action": 0
      }
    ],
    "permissions_levels_count": 100
  },
  "setting": {
    "iD": 1,
    "ENABLE_APP": 1,
    "DISABLE_NOTIFICATIONS": 1,
    "ENABLE_MULTI_EDIT": 1,
    "EXCHANGE_RATE": 3950,
    "OLD_EXCHANGE_RATE": 3950,
    "BUY_EXCHANGE_RATE": 3900,
    "BUY_EXCHANGE_RATE_OLD": 3900,
    "date": "2021-07-01 23:24:09",
    "currency": "DOLLAR_THREE_ZERO"
  },
  "login": true,
  "permission": true,
  "warehouse_employees": [
    {
      "iD": 1,
      "EmployeeID": 1,
      "WarehouseID": 1,
      "employees": null,
      "warehouse": {"iD": 1, "name": "مستودع القزاز"}
    },
    {
      "iD": 2,
      "EmployeeID": 1,
      "WarehouseID": 2,
      "employees": null,
      "warehouse": {"iD": 2, "name": "مستودع الصفوري"}
    }
  ]
};
const printOptions = {
  "requestIDs": [640],
  "actionMessage": "orders",
  "printerOptions": {
    "language": 1,
    "sendToClient": null,
    "copies": 1,
    "startEndPage": null,
    "printOptionsEnum": 3,
    "printerName": "HP LaserJet Pro MFP M26nw[2CABD4]",
    "printerNameLable": null,
    "printPaperSize": 2,
    "iD": 2,
    "serverResponse": null
  },
  "user": null,
  "command": "exit",
  "isArabic": true,
  "isPrintCall": false,
  "exit": false,
  "ASC": false,
  "shipmentDetails": null,
  "printLabel": false,
  "reportOptions": {"reportHeader": "DSS"},
  "showBarcodes": false,
  "imgLinkAndroidQRCode":
      "http://saffoury.com/main?obj=Orders&action=list&d=H4sIAAAAAAAAAKuuBQBDv6ajAgAAAA%3D%3D",
  "printProductsLabels": false,
  "barcode": null,
  "sortBy": 0,
  "cutRequestSort": 1,
  "cutRequestPrintOption": 1,
  "moneyFundSort": 1,
  "dateObject": null,
  "date": null,
  "responseType": 0,
  "requestFrom": 0,
  "currency": null,
  "warehouse": null,
  "hideCargoInfo": false,
  "showPreviousBalance": false,
  "hideCustomerName": false,
  "dontPrintWasteProductLabel": true,
  "printAsCatalog": false,
  "collectSimilarProducts": false,
  "hideQuantity": false,
  "customQuantity": 0.0,
  "showProductStatus": false,
  "fillChangedProductsToAnotherColor": false,
  "smallVersion": false,
  "showTotalCounts": false,
  "showPurchasesPrice": false,
  "showSubTotals": false,
  "showProductParents": false,
  "showReporting": false,
  "convertToSYP": false,
  "sypToday": 0.0,
  "showInvoiceRefunds": false,
  "hideBalanceDue": false,
  "hidePaymentAmount": true,
  "hideEmployeeName": true,
  "hideUnitAndTotalPrice": true,
  "hideTerms": true,
  "hideAddressAndPhone": false,
  "hideCurrency": true,
  "viewAsLedger": false,
  "threeZeroPrice": true,
  "reportHeader": null,
  "reportFooter": null,
  "androidObj": null,
  "isList": false,
  "customClassName": false,
  "invoiceProductTypeOptions": 0,
  "invoiceProductTypeOptionsName": "قص رول",
  "printProductOptions": 0,
  "invoiceOptions": 0,
  "generatedFileNameToDownload": null,
  "filesNameToDownload": null,
  "iD": -1,
  "serverResponse": null
};
