// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDjOF_6BDh4ljqm3ioCbLeCgdfmYKd02J0',
//     appId: '1:1052345970497:web:840574b94dfdfc246ebbc0',
//     messagingSenderId: '1052345970497',
//     projectId: 'falconpaper-c7f81',
//     authDomain: 'falconpaper-c7f81.firebaseapp.com',
//     storageBucket: 'falconpaper-c7f81.firebasestorage.app',
//     measurementId: 'G-B3ZHMF5ENX',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAFeRL-QjgTYgd3QqDMjLBjcURO-im7Jbo',
//     appId: '1:1052345970497:android:1af5a9e31e446ea76ebbc0',
//     messagingSenderId: '1052345970497',
//     projectId: 'falconpaper-c7f81',
//     storageBucket: 'falconpaper-c7f81.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAJLdvc0upGh7P-TVGL5CuMZ-sy-5ZhSTE',
//     appId: '1:1052345970497:ios:4614c264e96bf2e66ebbc0',
//     messagingSenderId: '1052345970497',
//     projectId: 'falconpaper-c7f81',
//     storageBucket: 'falconpaper-c7f81.firebasestorage.app',
//     iosBundleId: 'com.falcon.falconpaper',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAJLdvc0upGh7P-TVGL5CuMZ-sy-5ZhSTE',
//     appId: '1:1052345970497:ios:f857d66c891aebb96ebbc0',
//     messagingSenderId: '1052345970497',
//     projectId: 'falconpaper-c7f81',
//     storageBucket: 'falconpaper-c7f81.firebasestorage.app',
//     iosBundleId: 'com.example.flutterSaffouryPaper',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyDjOF_6BDh4ljqm3ioCbLeCgdfmYKd02J0',
//     appId: '1:1052345970497:web:486b901903ed40246ebbc0',
//     messagingSenderId: '1052345970497',
//     projectId: 'falconpaper-c7f81',
//     authDomain: 'falconpaper-c7f81.firebaseapp.com',
//     storageBucket: 'falconpaper-c7f81.firebasestorage.app',
//     measurementId: 'G-H7QHQDG3X3',
//   );
// }
