name: flutter_view_controller
description: A Flutter package to generate view.
homepage: https://github.com/geaquzzil/flutter_view_controler
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.3.2"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bottom_navy_bar: ^6.0.0
  flutter_advanced_drawer: 1.3.2
  http:  ^0.13.4
  pretty_http_logger: ^0.2.1
  json_annotation: ^4.0.1
  reflectable: ^3.0.2
  secure_random: ^1.0.0
  encrypt: ^5.0.1
  intl: ^0.17.0
  loadmore: ^2.0.1
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.23.0+1 # Used to render svg images
  google_fonts: ^3.0.1 # Used to include google fonts
  flutter_rating_bar: ^4.0.0 # Used for show product star ratings
  responsive_framework: ^0.2.0
  flutter_icons: ^1.1.0
  smooth_page_indicator: ^1.0.0+2
  carousel_slider: ^4.1.1
  cached_network_image: ^3.2.1
  palette_generator: ^0.3.3+1
  intl_converter: ^1.0.0
  provider: ^6.0.3
  icon_badge: ^1.0.0
  shimmer: ^2.0.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  bloc_concurrency: ^0.2.0
  sliding_up_panel: ^2.0.0+1
  latlng: ^0.2.0
  flutter_map: ^3.0.0
  latlong2: ^0.8.1
  hidden_drawer_menu: ^3.0.1
  lottie: ^1.3.0
  flutter_staggered_grid_view: ^0.6.1
  sprung: ^3.0.0
  shared_preferences: ^2.0.15
  flutter_native_splash: ^2.1.6
  flutter_spinkit: ^5.1.0
  supercharged: ^2.1.1
  paginated_search_bar: ^1.1.2
  custom_pop_up_menu: ^1.2.4
  animate_icons: ^2.0.0 
  flutter_form_builder: ^7.4.0
  form_builder_validators: ^8.2.0
  form_builder_extra_fields: ^8.2.0
  # file_picker: ^5.0.1
  path_provider: ^2.0.11
  badges: ^2.0.3
  jsonize: ^1.5.0
  easy_web_view: ^1.6.0
  flutter_html: ^3.0.0-alpha.5
  printing: ^5.9.3
  flutter_html_to_pdf: ^0.7.0
  webcontent_converter: ^0.0.7+2
  window_manager: ^0.2.7
  path: ^1.8.2
  dashboard: ^0.0.2+4
  auto_size_text: ^3.0.0
  popover: ^0.2.6+3
  just_the_tooltip: ^0.0.12
  pdf: ^3.8.3
  number_to_character: ^0.0.11
  
  # analyzer: ^4.2.0
  
dev_dependencies:
  # mockito: ^5.0.16
  build_runner: ^2.0.5
  # json_serializable: ^6.3.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/Img_0.png
  android: true
  ios: true
  web: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
